### PR TITLE
Minor Changes

### PR DESCRIPTION
**Pull request by Shaggs**
Just some minor changes to allow for easier user access

removed folder as its not needed

### CODE REVIEW

**Comment by adambrenecki** [comment]
Hi,

Thanks for this! I didn't even know anyone was using it!

This has been unmaintained for a while, but I've actually been thinking about getting it working again (my  brigade started using Swissphone FFRS for mobile paging, but it doesn't check for the `*CFSRES` response string, so it makes these really obnoxious siren noises for pager messages about cleaning duties and fire ban days).

**Comment by Shaggs** [comment]
Were starting to use mycfs crew but if you look at my project I've done a
full turnout system using python

Thanks

Shane Rees

0410-181-908

sent via mobile

**Comment by Shaggs** [comment]
Are you able to delete my comment ?

**Comment by Shaggs** [comment]
Didn't know its posted for all to see

**Comment by Shaggs** [comment]
ill try and add more changes tomorrow

**Comment by Shaggs** [comment]
Hi Adam,
              Just wondering if its possible to combine the scraper and
daemon? I find the scraper is good to look at to make sure daemon is
running correctly. O have tried but have had no luck

Cheers

Shane

**Pull request merged**
